[package]
name = "bmp280-server"
version = "0.1.0"
authors = ["Aatif Syed <aatifsyedyp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp280 = "0.2.1"
hex = "0.4.2"
simple-error = "0.2.3"
structopt = "0.3.21"
